# Generated by Django 2.2.1 on 2019-05-27 00:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('registrationNumber', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('telephoneNumber', models.IntegerField(null=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('delete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited', models.DateTimeField(blank=True, default=None, null=True)),
                ('teacher', models.ForeignKey(on_delete=models.SET(-1), to='Teacher.Teacher')),
            ],
            options={
                'db_table': 'Student',
            },
        ),
    ]
