# Generated by Django 2.2.1 on 2019-05-27 00:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('telephoneNumber', models.IntegerField(null=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('yearsOfExperience', models.IntegerField()),
                ('delete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'Teacher',
            },
        ),
    ]
